trigger:
  branches:
    include:
      - main

pool:
  name: 'Azure Pipelines'   # your pool name

variables:
  sshServiceConnection: 'RnD Droplet (DigitalOcean)'
  deployDir: '/home/dev/webapp/todo-list-app'
  branch: 'main'
  composeFile: 'compose.yaml'
  useSudo: 'false'

stages:
- stage: Deploy
  jobs:
  - job: Redeploy
    steps:
    - checkout: none
    - task: SSH@0
      displayName: Update repo and restart containers
      inputs:
        sshEndpoint: '$(sshServiceConnection)'
        runOptions: commands
        readyTimeout: '20000'
        commands: |
          set -e
          run() { if [ "$(useSudo)" = "true" ]; then sudo "$@"; else "$@"; fi; }
          cd "$(deployDir)"
          git fetch --depth 1 origin "$(branch)"
          git checkout -f "$(branch)"
          git reset --hard "origin/$(branch)"
          git clean -fd
          [ -f "$(composeFile)" ] || { echo "Missing $(composeFile)"; exit 1; }
          run docker compose -f "$(composeFile)" down --remove-orphans || true
          run docker compose -f "$(composeFile)" up -d --build