trigger:
  branches:
    include:
    - main
pool:
  name: 'Azure Pipelines'
variables:
  - name: sshServiceConnection
    value: 'RnD Droplet (DigitalOcean)'
  - name: deployDir
    value: '/home/dev/'
  - name: branch
    value: 'main'
  - name: composeFile
    value: 'compose.yaml'
  - name: useSudo
    value: 'false'
stages:
- stage: Deploy
  jobs:
  - job: Redeploy
    steps:
    - task: SSH@0
      displayName: Update repo and restart containers
      inputs:
        sshEndpoint: '$(sshServiceConnection)'
        runOptions: commands
        readyTimeout: '20000'
        commands: |-
          set -e
          echo "--- Running as user: ---"
          whoami
          echo "--- Starting in directory: ---"
          pwd

          echo "--- Attempting to change to deployment directory ---"
          cd /home/dev/

          echo "--- Now in directory: ---"
          pwd
          echo "--- Listing contents: ---"
          ls -la

          echo "--- Fetching latest changes from git ---"
          git fetch --depth 1 origin "$(branch)"
          git checkout -f "$(branch)"
          git reset --hard "origin/$(branch)"
          git clean -fd
          [ -f "$(composeFile)" ] || { echo "Missing $(composeFile)"; exit 1; }
          docker compose -f "$(composeFile)" down --remove-orphans || true
          docker compose -f "$(composeFile)" up -d --build