trigger:
  branches:
    include:
    - main
pool:
  name: 'Azure Pipelines'
variables:
  - name: sshServiceConnection
    value: 'RnD Droplet (DigitalOcean)'
  - name: deployDir
    value: '/home/dev/webapp/todo-list-app'
  - name: branch
    value: 'main'
  - name: composeFile
    value: 'compose.yaml'
  - name: useSudo
    value: 'false'
stages:
- stage: Deploy
  jobs:
  - job: Redeploy
    steps:
    - task: SSH@0
      displayName: Update repo and restart containers
      inputs:
        sshEndpoint: '$(sshServiceConnection)'
        runOptions: commands
        readyTimeout: '20000'
        commands: |-
          set -e
          cd "$(deployDir)"
          /usr/bin/git fetch --depth 1 origin "$(branch)"
          /usr/bin/git checkout -f "$(branch)"
          /usr/bin/git reset --hard "origin/$(branch)"
          /usr/bin/git clean -fd
          [ -f "$(composeFile)" ] || { echo "Missing $(composeFile)"; exit 1; }
          docker compose -f "$(composeFile)" down --remove-orphans || true
          docker compose -f "$(composeFile)" up -d --build